### ISSUE TITLE
"Deep search" a separate page from the main page

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#514] opened 2018-09-25 14:03 UTC
The main page search should include by title, by choreographer, by type, and by formation. Possibly a single 'includes figure' or 'doesn't include figure.'

For deep search operations (nested searches, grouped searches, much of our current search operation), go to an 'advanced search page'. 

I put forth that we open this "new" section of the site up before we add more search operation to the main page.

**Comment by dcmorse** [comment] 2018-09-25 15:18
What do you mean when you say people can search by 'type'?  Is that the same as by formation?

difficulty `4` for splitting it off to a new search page, and simplifying the main search page. I'm not sure how hard it would be to include searching by formation or by one figure.

**Comment by cranhandler** [comment] 2018-09-25 15:20
Type = contra, circle mixer, square
Formation = proper, improper

Right now we have these in the same column, but they're really not the same. Hmm. We should not get bogged down in disambiguating 'type' and 'formation' in order to make the new search page though.

**Comment by dcmorse** [comment] 2020-02-09 14:18
Closing as dupe of #563.
Also: lolol  difficulty: `4`.

**Closed by dcmorse** 2020-02-09 14:18 UTC
Labels: 4, blocked
